version: "2"
linters:
  default: all
  disable:
    - mnd
    - wsl
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
    varnamelen:
      min-name-length: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/npavlov/go-password-manager)
    goimports:
      local-prefixes:
        - github.com/npavlov/go-password-manager
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
