coverage:
  round: down
  range: '60...100'
  status:
    patch:
      default:
        target: 50%
    project:
      default:
        target: 80%
        threshold: 0%
github_checks:
  annotations: false
ignore:
  - "internal/server/db"
  - "internal/server/buildinfo"
  - "internal/server/adapter"
  - "internal/test_utils"
  - "internal/client/model"
  - "gen"