version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword  # Replace with a strong password
      - POSTGRES_DB=praktikum
    ports:
      - "5432:5432"  # Expose PostgreSQL for host machine access (optional)
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"  # Expose Redis for host machine access (optional)
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"  # Kafka broker port
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"  # Zookeeper port
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:1.46
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411  # Enable Zipkin endpoint
    ports:
      - "5775:5775/udp"    # UDP port for jaeger-agent
      - "6831:6831/udp"    # UDP port for agent with compact Thrift protocol
      - "6832:6832/udp"    # UDP port for agent with binary Thrift protocol
      - "5778:5778"        # HTTP port for agent configuration
      - "16686:16686"      # HTTP port for Jaeger UI
      - "14268:14268"      # HTTP port for collector
      - "14250:14250"      # GRPC port for collector
      - "9411:9411"        # HTTP port for Zipkin compatibility
      - "4318:4318"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
