version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword  # Replace with a strong password
      - POSTGRES_DB=yourdb
    ports:
      - "5432:5432"  # Expose PostgreSQL for host machine access (optional)
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"  # Expose Redis for host machine access (optional)
    networks:
      - app-network

  server:
    build:
      context: ..
      dockerfile: ./deployment/dockerfile.debug
    networks:
      - app-network
    ports:
      - "9090:9090"    # Server application port
      - "40000:40000"  # Delve debugging port
    environment:
      - ADDRESS=:9090  # Replace with the address your server listens on
      - DATABASE_DSN=postgres://postgres:yourpassword@postgres:5432/yourdb?sslmode=disable
      - JWT_SECRET=random
      - REDIS=redis:6379  # Redis hostname and port
    command: dlv exec /app/server --headless --listen=:40000 --api-version=2 --log --accept-multiclient

networks:
  app-network:
    driver: bridge
