version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword  # Replace with a strong password
      - POSTGRES_DB=yourdb
    ports:
      - "5432:5432"  # Expose PostgreSQL for host machine access (optional)
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"  # Expose Redis for host machine access (optional)
    networks:
      - app-network

  server:
    build:
      context: ..
      dockerfile: ./deployment/dockerfile
      args:
        VERSION: "1.0.0"
        DATE: "${BUILD_DATE:-$(date -u +%Y-%m-%d)}"
        COMMIT: "${GIT_COMMIT:-$(git rev-parse HEAD)}"
    networks:
      - app-network
    ports:
      - "8082:8082"    # Server application port
    environment:
      - ADDRESS=server:9090  # Replace with the address your server listens on
      - DATABASE_DSN=postgres://postgres:yourpassword@postgres:5432/yourdb?sslmode=disable
      - JWT_SECRET=random
      - REDIS=redis:6379  # Redis hostname and port
    command: /app/server


networks:
  app-network:
    driver: bridge
