// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Password struct {
	ID        pgtype.UUID      `db:"id"`
	UserID    pgtype.UUID      `db:"user_id"`
	Name      string           `db:"name"`
	Login     string           `db:"login"`
	Password  string           `db:"password"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at"`
}

type User struct {
	ID            pgtype.UUID `db:"id"`
	Username      string      `db:"username"`
	Email         string      `db:"email"`
	Password      string      `db:"password"`
	EncryptionKey string      `db:"encryption_key"`
}
