name: Build Go Binaries and Server Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          go install github.com/pressly/goose/v3/cmd/goose@latest
          go install github.com/go-delve/delve/cmd/dlv@latest
          curl -sSf https://atlasgo.sh | sh
          curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-$(uname -s)-$(uname -m) -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf

      - name: Build Client Binaries (all platforms)
        run: make build-client-all

      - name: Build Server Binary
        run: make build-server

      - name: Build Server Docker Image
        run: make build-server-docker