name: Test and coverage

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Run coverage
        run: make test
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./coverage.out # optional
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}